version: '3'

services:
  postgres:
    image: postgres:16.1
    container_name: mypostgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
