version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: mypostgres
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"

  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://your_username:your_password@mypostgres:5432/your_database_name
